module.exports = {
  buildEnv: {
    APP_DIR: './app',
    BUILD_DIR: './tasks',
    DEV_DIR: './dev',
    METRICS_DIR: './metrics',
    PROD_DIR: './dist',
    TEMP_DIR: './tmp',
    VENDOR_DIR: './vendor',
    ASSETS_DIR: './assets',
    JS_HINT_FILE: '.jshintrc',
    DEV_PORT: 9000,
    PROD_PORT: 8080
  },
  annotate: require('gulp-ng-annotate'),
  args: require('yargs').argv,
  changed: require('gulp-changed'),
  gulp: require('gulp'),
  inject: require('gulp-inject'),
  jsHint: require('gulp-jshint'),
  karma: require('karma'),
  karmaConfig: require("karma/lib/config").parseConfig,
  less: require('gulp-less'),
  minifyCSS: require('gulp-cssnano'),
  minifyHTML: require('gulp-htmlmin'),  
  path: require('path'),
  plato: require('plato'),
  rimraf: require('gulp-rimraf'),
  runSequence: require('run-sequence'),
  templateCache: require('gulp-angular-templatecache'),
  uglify: require('gulp-uglify'),
  useref: require('gulp-useref'),
  util: require("gulp-util"),
  webServer: require('gulp-webserver'),
  wiredep: require('wiredep').stream,
  projects: ['cars']
};