module.exports = {
  buildEnv: {
    APP_DIR: './apps',
    APP_FULL_DIR: './src/apps',
    APP_SRC: './src',
    ASSETS_DIR: '/assets',
    BUILD_DIR: './tasks',
    CORE_DIR: 'core',
    COVERAGE_DIR: './coverage',
    DEV_DIR: './tmp_dev',
    JS_HINT_FILE: '.jshintrc',
    LOCALS_DIR: 'locals',
    METRICS_DIR: './metrics',
    PROD_DIR: './prod',
    TEMP_DIR: './tmp',
    VENDOR_DIR: './vendor'
  },
  tasksEnv: {
    defaultKarmaBrowser: 'PhantomJS',
    defaultServerPort: 5101,
    stylesPaths: ['includes', 'components', 'layout', 'layouts'],
    stylesSufix: 'less',
    viewsSufix: 'html',
    viewsLocals: true
  },
  annotate: require('gulp-ng-annotate'),
  args: require('yargs').argv,
  changed: require('gulp-changed'),
  changelog: require('conventional-changelog'),
  fs: require('fs'),
  gulp: require('gulp'),
  gulpIf: require('gulp-if'),
  inject: require('gulp-inject'),
  jade: require('gulp-jade'),
  jsHint: require('gulp-jshint'),
  karma: require('karma'),
  karmaConfig: require("karma/lib/config").parseConfig,
  less: require('gulp-less'),  
  minifyCSS: require('gulp-cssnano'),
  minifyHTML: require('gulp-htmlmin'),
  open: require('open'),
  path: require('path'),
  plato: require('plato'),
  rename: require('gulp-rename'),
  rimraf: require('gulp-rimraf'),
  runSequence: require('run-sequence'),
  sass: require('gulp-sass'),
  templateCache: require('gulp-angular-templatecache'),
  uglify: require('gulp-uglify'),
  useref: require('gulp-useref'),
  util: require('gulp-util'),
  webServer: require('gulp-webserver'),
  wiredep: require('wiredep').stream
};